### ISSUE TITLE
xpay가 정상작동하지 않는 문제

### ISSUE THREAD

**Issue by bjrambo** [bjrambo/nurigo#107]
CentOS7
mysql-5.7.16
apache-2.4.23
php-7.0.12
로 무사히 업한 후에 누리고 쇼핑몰 테스하고 있습니다.
일단, 다른 것은 이상없는데
 
바로구매 클릭시
Parse error: syntax error, unexpected 'new' (T_NEW) in l/modules/epay/plugins/xpay/xpay.plugin.php on line 88
Parse error: syntax error, unexpected 'new' (T_NEW) in l/modules/epay/plugins/xpay/xpay.plugin.php on line 145

에러 발생하면서 실행 안됩니다.
 
장바구니 클릭시
Fatal error: Uncaught Error: Using $this when not in object context in /modules/nproduct/nproduct.item.php:73 Stack trace: #0 /files/cache/template_compiled/f2fbb4f525d4085b986a054cdc4c57e7.compiled.php(85): nproductItem::printPrice(0) #1 /classes/template/TemplateHandler.class.php(384): include('/k...') #2 /classes/template/TemplateHandler.class.php(175): TemplateHandler->_fetch('file:///na...') #3 /classes/display/HTMLDisplayHandler.php(61): TemplateHandler->compile('./modules/ncart...', 'cartitems.html') #4 /classes/display/DisplayHandler.class.php(65): HTMLDisplayHandler->toDoc(Object(ncartView)) #5 /classes/module/ModuleHandler.class.php(1120): DisplayHandler->printContent(Object(ncartView)) #6 /index.php(59): ModuleHandler->displayContent(Object(n in /modules/nproduct/nproduct.item.php on line 73 
 
 
목록보기 버튼은 제대로 잘 작동합니다.
 
위의  오동작으로 말미암아 더 이상 테스트 진전이 없습니다.
 
바쁘시더라도 에러 해결 부탁드립니다.
 
감사합니다.

**Comment by bjrambo** [comment]
Fix parse error in 9fc6605

**Comment by bjrambo** [comment]
Fix Uncaught Error in c7e9b0e
